---
- name: This playbook creates a fil or dir
  hosts: all
    #  become: true
    #  gather_facts: no
  tasks: 
  - name: creating a file
    file:
      path: /home/ansadmin/dir1
      state: directory
