---
- name: This playbook uninstall httpd
  hosts: all
  become: true
  tasks:
  - name: stop apache2 service
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Dabian"

  - name: uninstall apache2 
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Dabian"

  - name: Stop httpd Service
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: Unisatll httpd service
    yum:
      name: httpd
      state: remove
    when: ansible_os_family == "RedHat"


